name = "airwartrail-dashboard"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-07-17"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false

[assets]
binding = "ASSETS"
directory = "./dist"

[[r2_buckets]]
binding = "AIRWARTRAIL_ASSETS"
bucket_name = "airwartrail-assets"
preview_bucket_name = "airwartrail-assets-dev"

[observability]
enabled = true

[vars]
BETTER_AUTH_URL = "https://dashboard.airwartrail.com"
PUBLIC_BUNNY_LIBRARY_ID = "416789"
PUBLIC_BUNNY_STREAM_CDN = "vz-91a12c63-3f2.b-cdn.net"
PUBLIC_R2_BUCKET_URL = "https://assets.airwartrail.com"
TURNSTILE_PUBLIC_KEY = "3x00000000000000000000FF"