/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardUploadRouteImport } from './routes/_dashboard/upload'
import { Route as DashboardUserUserIdRouteImport } from './routes/_dashboard/user/$userId'
import { Route as DashboardLibraryNewRouteImport } from './routes/_dashboard/library/new'
import { Route as DashboardLibraryLibraryIdVideosRouteImport } from './routes/_dashboard/library/$libraryId/videos'
import { Route as DashboardLibraryLibraryIdEditLibraryRouteImport } from './routes/_dashboard/library/$libraryId/edit-library'
import { Route as DashboardLibraryLibraryIdEditVideoVideoIdRouteImport } from './routes/_dashboard/library/$libraryId/edit-video/$videoId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserUserIdRoute = DashboardUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryNewRoute = DashboardLibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryLibraryIdVideosRoute =
  DashboardLibraryLibraryIdVideosRouteImport.update({
    id: '/library/$libraryId/videos',
    path: '/library/$libraryId/videos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdEditLibraryRoute =
  DashboardLibraryLibraryIdEditLibraryRouteImport.update({
    id: '/library/$libraryId/edit-library',
    path: '/library/$libraryId/edit-library',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdEditVideoVideoIdRoute =
  DashboardLibraryLibraryIdEditVideoVideoIdRouteImport.update({
    id: '/library/$libraryId/edit-video/$videoId',
    path: '/library/$libraryId/edit-video/$videoId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof DashboardUploadRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/library/new': typeof DashboardLibraryNewRoute
  '/user/$userId': typeof DashboardUserUserIdRoute
  '/library/$libraryId/edit-library': typeof DashboardLibraryLibraryIdEditLibraryRoute
  '/library/$libraryId/videos': typeof DashboardLibraryLibraryIdVideosRoute
  '/library/$libraryId/edit-video/$videoId': typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof DashboardUploadRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/library/new': typeof DashboardLibraryNewRoute
  '/user/$userId': typeof DashboardUserUserIdRoute
  '/library/$libraryId/edit-library': typeof DashboardLibraryLibraryIdEditLibraryRoute
  '/library/$libraryId/videos': typeof DashboardLibraryLibraryIdVideosRoute
  '/library/$libraryId/edit-video/$videoId': typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/upload': typeof DashboardUploadRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_dashboard/library/new': typeof DashboardLibraryNewRoute
  '/_dashboard/user/$userId': typeof DashboardUserUserIdRoute
  '/_dashboard/library/$libraryId/edit-library': typeof DashboardLibraryLibraryIdEditLibraryRoute
  '/_dashboard/library/$libraryId/videos': typeof DashboardLibraryLibraryIdVideosRoute
  '/_dashboard/library/$libraryId/edit-video/$videoId': typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/library/new'
    | '/user/$userId'
    | '/library/$libraryId/edit-library'
    | '/library/$libraryId/videos'
    | '/library/$libraryId/edit-video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/library/new'
    | '/user/$userId'
    | '/library/$libraryId/edit-library'
    | '/library/$libraryId/videos'
    | '/library/$libraryId/edit-video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/upload'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_dashboard/library/new'
    | '/_dashboard/user/$userId'
    | '/_dashboard/library/$libraryId/edit-library'
    | '/_dashboard/library/$libraryId/videos'
    | '/_dashboard/library/$libraryId/edit-video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/upload': {
      id: '/_dashboard/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/user/$userId': {
      id: '/_dashboard/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof DashboardUserUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/new': {
      id: '/_dashboard/library/new'
      path: '/library/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof DashboardLibraryNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/videos': {
      id: '/_dashboard/library/$libraryId/videos'
      path: '/library/$libraryId/videos'
      fullPath: '/library/$libraryId/videos'
      preLoaderRoute: typeof DashboardLibraryLibraryIdVideosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/edit-library': {
      id: '/_dashboard/library/$libraryId/edit-library'
      path: '/library/$libraryId/edit-library'
      fullPath: '/library/$libraryId/edit-library'
      preLoaderRoute: typeof DashboardLibraryLibraryIdEditLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/edit-video/$videoId': {
      id: '/_dashboard/library/$libraryId/edit-video/$videoId'
      path: '/library/$libraryId/edit-video/$videoId'
      fullPath: '/library/$libraryId/edit-video/$videoId'
      preLoaderRoute: typeof DashboardLibraryLibraryIdEditVideoVideoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardLibraryNewRoute: typeof DashboardLibraryNewRoute
  DashboardUserUserIdRoute: typeof DashboardUserUserIdRoute
  DashboardLibraryLibraryIdEditLibraryRoute: typeof DashboardLibraryLibraryIdEditLibraryRoute
  DashboardLibraryLibraryIdVideosRoute: typeof DashboardLibraryLibraryIdVideosRoute
  DashboardLibraryLibraryIdEditVideoVideoIdRoute: typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardLibraryNewRoute: DashboardLibraryNewRoute,
  DashboardUserUserIdRoute: DashboardUserUserIdRoute,
  DashboardLibraryLibraryIdEditLibraryRoute:
    DashboardLibraryLibraryIdEditLibraryRoute,
  DashboardLibraryLibraryIdVideosRoute: DashboardLibraryLibraryIdVideosRoute,
  DashboardLibraryLibraryIdEditVideoVideoIdRoute:
    DashboardLibraryLibraryIdEditVideoVideoIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
