/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardUploadRouteImport } from './routes/_dashboard/upload'
import { Route as DashboardPlaylistsRouteImport } from './routes/_dashboard/playlists'
import { Route as DashboardLibrariesRouteImport } from './routes/_dashboard/libraries'
import { Route as DashboardTagsIndexRouteImport } from './routes/_dashboard/tags/index'
import { Route as DashboardImagesIndexRouteImport } from './routes/_dashboard/images/index'
import { Route as DashboardBlogPostsIndexRouteImport } from './routes/_dashboard/blog-posts/index'
import { Route as DashboardApiKeysIndexRouteImport } from './routes/_dashboard/api-keys/index'
import { Route as DashboardUserUserIdRouteImport } from './routes/_dashboard/user/$userId'
import { Route as DashboardLibraryCreateLibraryRouteImport } from './routes/_dashboard/library/create-library'
import { Route as DashboardImagesUploadRouteImport } from './routes/_dashboard/images/upload'
import { Route as DashboardBlogPostsCreatePostRouteImport } from './routes/_dashboard/blog-posts/create-post'
import { Route as DashboardApiKeysKeyIdRouteImport } from './routes/_dashboard/api-keys/$keyId'
import { Route as DashboardImagesAlbumsIndexRouteImport } from './routes/_dashboard/images/albums/index'
import { Route as DashboardLibraryEditLibraryLibraryIdRouteImport } from './routes/_dashboard/library/edit-library/$libraryId'
import { Route as DashboardLibraryLibraryIdVideosRouteImport } from './routes/_dashboard/library/$libraryId/videos'
import { Route as DashboardLibraryLibraryIdPlaylistsRouteImport } from './routes/_dashboard/library/$libraryId/playlists'
import { Route as DashboardLibraryLibraryIdCreatePlaylistRouteImport } from './routes/_dashboard/library/$libraryId/create-playlist'
import { Route as DashboardImagesEditImageImageIdRouteImport } from './routes/_dashboard/images/edit-image/$imageId'
import { Route as DashboardImagesAlbumsCreateAlbumRouteImport } from './routes/_dashboard/images/albums/create-album'
import { Route as DashboardImagesAlbumsAlbumIdRouteImport } from './routes/_dashboard/images/albums/$albumId'
import { Route as DashboardBlogPostsEditPostPostIdRouteImport } from './routes/_dashboard/blog-posts/edit-post/$postId'
import { Route as DashboardLibraryLibraryIdPlaylistPlaylistIdRouteImport } from './routes/_dashboard/library/$libraryId/playlist/$playlistId'
import { Route as DashboardLibraryLibraryIdEditVideoVideoIdRouteImport } from './routes/_dashboard/library/$libraryId/edit-video/$videoId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaylistsRoute = DashboardPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibrariesRoute = DashboardLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagsIndexRoute = DashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImagesIndexRoute = DashboardImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogPostsIndexRoute = DashboardBlogPostsIndexRouteImport.update({
  id: '/blog-posts/',
  path: '/blog-posts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysIndexRoute = DashboardApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserUserIdRoute = DashboardUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryCreateLibraryRoute =
  DashboardLibraryCreateLibraryRouteImport.update({
    id: '/library/create-library',
    path: '/library/create-library',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardImagesUploadRoute = DashboardImagesUploadRouteImport.update({
  id: '/images/upload',
  path: '/images/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogPostsCreatePostRoute =
  DashboardBlogPostsCreatePostRouteImport.update({
    id: '/blog-posts/create-post',
    path: '/blog-posts/create-post',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApiKeysKeyIdRoute = DashboardApiKeysKeyIdRouteImport.update({
  id: '/api-keys/$keyId',
  path: '/api-keys/$keyId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImagesAlbumsIndexRoute =
  DashboardImagesAlbumsIndexRouteImport.update({
    id: '/images/albums/',
    path: '/images/albums/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryEditLibraryLibraryIdRoute =
  DashboardLibraryEditLibraryLibraryIdRouteImport.update({
    id: '/library/edit-library/$libraryId',
    path: '/library/edit-library/$libraryId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdVideosRoute =
  DashboardLibraryLibraryIdVideosRouteImport.update({
    id: '/library/$libraryId/videos',
    path: '/library/$libraryId/videos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdPlaylistsRoute =
  DashboardLibraryLibraryIdPlaylistsRouteImport.update({
    id: '/library/$libraryId/playlists',
    path: '/library/$libraryId/playlists',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdCreatePlaylistRoute =
  DashboardLibraryLibraryIdCreatePlaylistRouteImport.update({
    id: '/library/$libraryId/create-playlist',
    path: '/library/$libraryId/create-playlist',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardImagesEditImageImageIdRoute =
  DashboardImagesEditImageImageIdRouteImport.update({
    id: '/images/edit-image/$imageId',
    path: '/images/edit-image/$imageId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardImagesAlbumsCreateAlbumRoute =
  DashboardImagesAlbumsCreateAlbumRouteImport.update({
    id: '/images/albums/create-album',
    path: '/images/albums/create-album',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardImagesAlbumsAlbumIdRoute =
  DashboardImagesAlbumsAlbumIdRouteImport.update({
    id: '/images/albums/$albumId',
    path: '/images/albums/$albumId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBlogPostsEditPostPostIdRoute =
  DashboardBlogPostsEditPostPostIdRouteImport.update({
    id: '/blog-posts/edit-post/$postId',
    path: '/blog-posts/edit-post/$postId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdPlaylistPlaylistIdRoute =
  DashboardLibraryLibraryIdPlaylistPlaylistIdRouteImport.update({
    id: '/library/$libraryId/playlist/$playlistId',
    path: '/library/$libraryId/playlist/$playlistId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLibraryLibraryIdEditVideoVideoIdRoute =
  DashboardLibraryLibraryIdEditVideoVideoIdRouteImport.update({
    id: '/library/$libraryId/edit-video/$videoId',
    path: '/library/$libraryId/edit-video/$videoId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/libraries': typeof DashboardLibrariesRoute
  '/playlists': typeof DashboardPlaylistsRoute
  '/upload': typeof DashboardUploadRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/api-keys/$keyId': typeof DashboardApiKeysKeyIdRoute
  '/blog-posts/create-post': typeof DashboardBlogPostsCreatePostRoute
  '/images/upload': typeof DashboardImagesUploadRoute
  '/library/create-library': typeof DashboardLibraryCreateLibraryRoute
  '/user/$userId': typeof DashboardUserUserIdRoute
  '/api-keys/': typeof DashboardApiKeysIndexRoute
  '/blog-posts/': typeof DashboardBlogPostsIndexRoute
  '/images/': typeof DashboardImagesIndexRoute
  '/tags/': typeof DashboardTagsIndexRoute
  '/blog-posts/edit-post/$postId': typeof DashboardBlogPostsEditPostPostIdRoute
  '/images/albums/$albumId': typeof DashboardImagesAlbumsAlbumIdRoute
  '/images/albums/create-album': typeof DashboardImagesAlbumsCreateAlbumRoute
  '/images/edit-image/$imageId': typeof DashboardImagesEditImageImageIdRoute
  '/library/$libraryId/create-playlist': typeof DashboardLibraryLibraryIdCreatePlaylistRoute
  '/library/$libraryId/playlists': typeof DashboardLibraryLibraryIdPlaylistsRoute
  '/library/$libraryId/videos': typeof DashboardLibraryLibraryIdVideosRoute
  '/library/edit-library/$libraryId': typeof DashboardLibraryEditLibraryLibraryIdRoute
  '/images/albums/': typeof DashboardImagesAlbumsIndexRoute
  '/library/$libraryId/edit-video/$videoId': typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
  '/library/$libraryId/playlist/$playlistId': typeof DashboardLibraryLibraryIdPlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/libraries': typeof DashboardLibrariesRoute
  '/playlists': typeof DashboardPlaylistsRoute
  '/upload': typeof DashboardUploadRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof DashboardIndexRoute
  '/api-keys/$keyId': typeof DashboardApiKeysKeyIdRoute
  '/blog-posts/create-post': typeof DashboardBlogPostsCreatePostRoute
  '/images/upload': typeof DashboardImagesUploadRoute
  '/library/create-library': typeof DashboardLibraryCreateLibraryRoute
  '/user/$userId': typeof DashboardUserUserIdRoute
  '/api-keys': typeof DashboardApiKeysIndexRoute
  '/blog-posts': typeof DashboardBlogPostsIndexRoute
  '/images': typeof DashboardImagesIndexRoute
  '/tags': typeof DashboardTagsIndexRoute
  '/blog-posts/edit-post/$postId': typeof DashboardBlogPostsEditPostPostIdRoute
  '/images/albums/$albumId': typeof DashboardImagesAlbumsAlbumIdRoute
  '/images/albums/create-album': typeof DashboardImagesAlbumsCreateAlbumRoute
  '/images/edit-image/$imageId': typeof DashboardImagesEditImageImageIdRoute
  '/library/$libraryId/create-playlist': typeof DashboardLibraryLibraryIdCreatePlaylistRoute
  '/library/$libraryId/playlists': typeof DashboardLibraryLibraryIdPlaylistsRoute
  '/library/$libraryId/videos': typeof DashboardLibraryLibraryIdVideosRoute
  '/library/edit-library/$libraryId': typeof DashboardLibraryEditLibraryLibraryIdRoute
  '/images/albums': typeof DashboardImagesAlbumsIndexRoute
  '/library/$libraryId/edit-video/$videoId': typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
  '/library/$libraryId/playlist/$playlistId': typeof DashboardLibraryLibraryIdPlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/libraries': typeof DashboardLibrariesRoute
  '/_dashboard/playlists': typeof DashboardPlaylistsRoute
  '/_dashboard/upload': typeof DashboardUploadRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/api-keys/$keyId': typeof DashboardApiKeysKeyIdRoute
  '/_dashboard/blog-posts/create-post': typeof DashboardBlogPostsCreatePostRoute
  '/_dashboard/images/upload': typeof DashboardImagesUploadRoute
  '/_dashboard/library/create-library': typeof DashboardLibraryCreateLibraryRoute
  '/_dashboard/user/$userId': typeof DashboardUserUserIdRoute
  '/_dashboard/api-keys/': typeof DashboardApiKeysIndexRoute
  '/_dashboard/blog-posts/': typeof DashboardBlogPostsIndexRoute
  '/_dashboard/images/': typeof DashboardImagesIndexRoute
  '/_dashboard/tags/': typeof DashboardTagsIndexRoute
  '/_dashboard/blog-posts/edit-post/$postId': typeof DashboardBlogPostsEditPostPostIdRoute
  '/_dashboard/images/albums/$albumId': typeof DashboardImagesAlbumsAlbumIdRoute
  '/_dashboard/images/albums/create-album': typeof DashboardImagesAlbumsCreateAlbumRoute
  '/_dashboard/images/edit-image/$imageId': typeof DashboardImagesEditImageImageIdRoute
  '/_dashboard/library/$libraryId/create-playlist': typeof DashboardLibraryLibraryIdCreatePlaylistRoute
  '/_dashboard/library/$libraryId/playlists': typeof DashboardLibraryLibraryIdPlaylistsRoute
  '/_dashboard/library/$libraryId/videos': typeof DashboardLibraryLibraryIdVideosRoute
  '/_dashboard/library/edit-library/$libraryId': typeof DashboardLibraryEditLibraryLibraryIdRoute
  '/_dashboard/images/albums/': typeof DashboardImagesAlbumsIndexRoute
  '/_dashboard/library/$libraryId/edit-video/$videoId': typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
  '/_dashboard/library/$libraryId/playlist/$playlistId': typeof DashboardLibraryLibraryIdPlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/libraries'
    | '/playlists'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/api-keys/$keyId'
    | '/blog-posts/create-post'
    | '/images/upload'
    | '/library/create-library'
    | '/user/$userId'
    | '/api-keys/'
    | '/blog-posts/'
    | '/images/'
    | '/tags/'
    | '/blog-posts/edit-post/$postId'
    | '/images/albums/$albumId'
    | '/images/albums/create-album'
    | '/images/edit-image/$imageId'
    | '/library/$libraryId/create-playlist'
    | '/library/$libraryId/playlists'
    | '/library/$libraryId/videos'
    | '/library/edit-library/$libraryId'
    | '/images/albums/'
    | '/library/$libraryId/edit-video/$videoId'
    | '/library/$libraryId/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/libraries'
    | '/playlists'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/api-keys/$keyId'
    | '/blog-posts/create-post'
    | '/images/upload'
    | '/library/create-library'
    | '/user/$userId'
    | '/api-keys'
    | '/blog-posts'
    | '/images'
    | '/tags'
    | '/blog-posts/edit-post/$postId'
    | '/images/albums/$albumId'
    | '/images/albums/create-album'
    | '/images/edit-image/$imageId'
    | '/library/$libraryId/create-playlist'
    | '/library/$libraryId/playlists'
    | '/library/$libraryId/videos'
    | '/library/edit-library/$libraryId'
    | '/images/albums'
    | '/library/$libraryId/edit-video/$videoId'
    | '/library/$libraryId/playlist/$playlistId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/libraries'
    | '/_dashboard/playlists'
    | '/_dashboard/upload'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_dashboard/'
    | '/_dashboard/api-keys/$keyId'
    | '/_dashboard/blog-posts/create-post'
    | '/_dashboard/images/upload'
    | '/_dashboard/library/create-library'
    | '/_dashboard/user/$userId'
    | '/_dashboard/api-keys/'
    | '/_dashboard/blog-posts/'
    | '/_dashboard/images/'
    | '/_dashboard/tags/'
    | '/_dashboard/blog-posts/edit-post/$postId'
    | '/_dashboard/images/albums/$albumId'
    | '/_dashboard/images/albums/create-album'
    | '/_dashboard/images/edit-image/$imageId'
    | '/_dashboard/library/$libraryId/create-playlist'
    | '/_dashboard/library/$libraryId/playlists'
    | '/_dashboard/library/$libraryId/videos'
    | '/_dashboard/library/edit-library/$libraryId'
    | '/_dashboard/images/albums/'
    | '/_dashboard/library/$libraryId/edit-video/$videoId'
    | '/_dashboard/library/$libraryId/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/upload': {
      id: '/_dashboard/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/playlists': {
      id: '/_dashboard/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof DashboardPlaylistsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/libraries': {
      id: '/_dashboard/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof DashboardLibrariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tags/': {
      id: '/_dashboard/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof DashboardTagsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/images/': {
      id: '/_dashboard/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof DashboardImagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blog-posts/': {
      id: '/_dashboard/blog-posts/'
      path: '/blog-posts'
      fullPath: '/blog-posts/'
      preLoaderRoute: typeof DashboardBlogPostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/api-keys/': {
      id: '/_dashboard/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof DashboardApiKeysIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/user/$userId': {
      id: '/_dashboard/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof DashboardUserUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/create-library': {
      id: '/_dashboard/library/create-library'
      path: '/library/create-library'
      fullPath: '/library/create-library'
      preLoaderRoute: typeof DashboardLibraryCreateLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/images/upload': {
      id: '/_dashboard/images/upload'
      path: '/images/upload'
      fullPath: '/images/upload'
      preLoaderRoute: typeof DashboardImagesUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blog-posts/create-post': {
      id: '/_dashboard/blog-posts/create-post'
      path: '/blog-posts/create-post'
      fullPath: '/blog-posts/create-post'
      preLoaderRoute: typeof DashboardBlogPostsCreatePostRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/api-keys/$keyId': {
      id: '/_dashboard/api-keys/$keyId'
      path: '/api-keys/$keyId'
      fullPath: '/api-keys/$keyId'
      preLoaderRoute: typeof DashboardApiKeysKeyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/images/albums/': {
      id: '/_dashboard/images/albums/'
      path: '/images/albums'
      fullPath: '/images/albums/'
      preLoaderRoute: typeof DashboardImagesAlbumsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/edit-library/$libraryId': {
      id: '/_dashboard/library/edit-library/$libraryId'
      path: '/library/edit-library/$libraryId'
      fullPath: '/library/edit-library/$libraryId'
      preLoaderRoute: typeof DashboardLibraryEditLibraryLibraryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/videos': {
      id: '/_dashboard/library/$libraryId/videos'
      path: '/library/$libraryId/videos'
      fullPath: '/library/$libraryId/videos'
      preLoaderRoute: typeof DashboardLibraryLibraryIdVideosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/playlists': {
      id: '/_dashboard/library/$libraryId/playlists'
      path: '/library/$libraryId/playlists'
      fullPath: '/library/$libraryId/playlists'
      preLoaderRoute: typeof DashboardLibraryLibraryIdPlaylistsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/create-playlist': {
      id: '/_dashboard/library/$libraryId/create-playlist'
      path: '/library/$libraryId/create-playlist'
      fullPath: '/library/$libraryId/create-playlist'
      preLoaderRoute: typeof DashboardLibraryLibraryIdCreatePlaylistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/images/edit-image/$imageId': {
      id: '/_dashboard/images/edit-image/$imageId'
      path: '/images/edit-image/$imageId'
      fullPath: '/images/edit-image/$imageId'
      preLoaderRoute: typeof DashboardImagesEditImageImageIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/images/albums/create-album': {
      id: '/_dashboard/images/albums/create-album'
      path: '/images/albums/create-album'
      fullPath: '/images/albums/create-album'
      preLoaderRoute: typeof DashboardImagesAlbumsCreateAlbumRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/images/albums/$albumId': {
      id: '/_dashboard/images/albums/$albumId'
      path: '/images/albums/$albumId'
      fullPath: '/images/albums/$albumId'
      preLoaderRoute: typeof DashboardImagesAlbumsAlbumIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blog-posts/edit-post/$postId': {
      id: '/_dashboard/blog-posts/edit-post/$postId'
      path: '/blog-posts/edit-post/$postId'
      fullPath: '/blog-posts/edit-post/$postId'
      preLoaderRoute: typeof DashboardBlogPostsEditPostPostIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/playlist/$playlistId': {
      id: '/_dashboard/library/$libraryId/playlist/$playlistId'
      path: '/library/$libraryId/playlist/$playlistId'
      fullPath: '/library/$libraryId/playlist/$playlistId'
      preLoaderRoute: typeof DashboardLibraryLibraryIdPlaylistPlaylistIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library/$libraryId/edit-video/$videoId': {
      id: '/_dashboard/library/$libraryId/edit-video/$videoId'
      path: '/library/$libraryId/edit-video/$videoId'
      fullPath: '/library/$libraryId/edit-video/$videoId'
      preLoaderRoute: typeof DashboardLibraryLibraryIdEditVideoVideoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardLibrariesRoute: typeof DashboardLibrariesRoute
  DashboardPlaylistsRoute: typeof DashboardPlaylistsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApiKeysKeyIdRoute: typeof DashboardApiKeysKeyIdRoute
  DashboardBlogPostsCreatePostRoute: typeof DashboardBlogPostsCreatePostRoute
  DashboardImagesUploadRoute: typeof DashboardImagesUploadRoute
  DashboardLibraryCreateLibraryRoute: typeof DashboardLibraryCreateLibraryRoute
  DashboardUserUserIdRoute: typeof DashboardUserUserIdRoute
  DashboardApiKeysIndexRoute: typeof DashboardApiKeysIndexRoute
  DashboardBlogPostsIndexRoute: typeof DashboardBlogPostsIndexRoute
  DashboardImagesIndexRoute: typeof DashboardImagesIndexRoute
  DashboardTagsIndexRoute: typeof DashboardTagsIndexRoute
  DashboardBlogPostsEditPostPostIdRoute: typeof DashboardBlogPostsEditPostPostIdRoute
  DashboardImagesAlbumsAlbumIdRoute: typeof DashboardImagesAlbumsAlbumIdRoute
  DashboardImagesAlbumsCreateAlbumRoute: typeof DashboardImagesAlbumsCreateAlbumRoute
  DashboardImagesEditImageImageIdRoute: typeof DashboardImagesEditImageImageIdRoute
  DashboardLibraryLibraryIdCreatePlaylistRoute: typeof DashboardLibraryLibraryIdCreatePlaylistRoute
  DashboardLibraryLibraryIdPlaylistsRoute: typeof DashboardLibraryLibraryIdPlaylistsRoute
  DashboardLibraryLibraryIdVideosRoute: typeof DashboardLibraryLibraryIdVideosRoute
  DashboardLibraryEditLibraryLibraryIdRoute: typeof DashboardLibraryEditLibraryLibraryIdRoute
  DashboardImagesAlbumsIndexRoute: typeof DashboardImagesAlbumsIndexRoute
  DashboardLibraryLibraryIdEditVideoVideoIdRoute: typeof DashboardLibraryLibraryIdEditVideoVideoIdRoute
  DashboardLibraryLibraryIdPlaylistPlaylistIdRoute: typeof DashboardLibraryLibraryIdPlaylistPlaylistIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLibrariesRoute: DashboardLibrariesRoute,
  DashboardPlaylistsRoute: DashboardPlaylistsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApiKeysKeyIdRoute: DashboardApiKeysKeyIdRoute,
  DashboardBlogPostsCreatePostRoute: DashboardBlogPostsCreatePostRoute,
  DashboardImagesUploadRoute: DashboardImagesUploadRoute,
  DashboardLibraryCreateLibraryRoute: DashboardLibraryCreateLibraryRoute,
  DashboardUserUserIdRoute: DashboardUserUserIdRoute,
  DashboardApiKeysIndexRoute: DashboardApiKeysIndexRoute,
  DashboardBlogPostsIndexRoute: DashboardBlogPostsIndexRoute,
  DashboardImagesIndexRoute: DashboardImagesIndexRoute,
  DashboardTagsIndexRoute: DashboardTagsIndexRoute,
  DashboardBlogPostsEditPostPostIdRoute: DashboardBlogPostsEditPostPostIdRoute,
  DashboardImagesAlbumsAlbumIdRoute: DashboardImagesAlbumsAlbumIdRoute,
  DashboardImagesAlbumsCreateAlbumRoute: DashboardImagesAlbumsCreateAlbumRoute,
  DashboardImagesEditImageImageIdRoute: DashboardImagesEditImageImageIdRoute,
  DashboardLibraryLibraryIdCreatePlaylistRoute:
    DashboardLibraryLibraryIdCreatePlaylistRoute,
  DashboardLibraryLibraryIdPlaylistsRoute:
    DashboardLibraryLibraryIdPlaylistsRoute,
  DashboardLibraryLibraryIdVideosRoute: DashboardLibraryLibraryIdVideosRoute,
  DashboardLibraryEditLibraryLibraryIdRoute:
    DashboardLibraryEditLibraryLibraryIdRoute,
  DashboardImagesAlbumsIndexRoute: DashboardImagesAlbumsIndexRoute,
  DashboardLibraryLibraryIdEditVideoVideoIdRoute:
    DashboardLibraryLibraryIdEditVideoVideoIdRoute,
  DashboardLibraryLibraryIdPlaylistPlaylistIdRoute:
    DashboardLibraryLibraryIdPlaylistPlaylistIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
